/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.smagp.controle.estoque_ti.gui;

import java.net.URL;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import br.smagp.controle.estoque_ti.gui.GUIEquipamento;
/**
 *
 * @author AllexOnRails
 */
public class GUIMenu extends javax.swing.JFrame {

    GUIEquipamento guiEquipamento = null;
    public boolean status;
    
    
    private JButton createImageButton(String texto, String uriAbsoluta) {
        URL uri = getClass().getResource(uriAbsoluta);
        JButton button = new JButton(texto, new ImageIcon(uri));
        button.setVerticalTextPosition(AbstractButton.BOTTOM);
        button.setHorizontalTextPosition(AbstractButton.CENTER);

        return button;
    }
    
    
    /**
     * Creates new form GUIMenu
     */
    public GUIMenu(boolean status) {
        dispose();
        this.setUndecorated(true);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.initComponents();
        this.status=status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbControle = new javax.swing.JButton();
        jbEquipamentos = new javax.swing.JButton();
        jbTecnicos = new javax.swing.JButton();
        jbChefias = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbOrgaos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbControle.setBackground(new java.awt.Color(255, 255, 255));
        jbControle.setForeground(new java.awt.Color(204, 204, 204));
        jbControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbControle.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbControle.setBorderPainted(false);
        jbControle.setFocusCycleRoot(true);
        jbControle.setFocusable(false);
        jbControle.setOpaque(false);
        jbControle.setRequestFocusEnabled(false);
        jbControle.setRolloverEnabled(false);
        jbControle.setVerifyInputWhenFocusTarget(false);

        jbEquipamentos.setBackground(new java.awt.Color(255, 255, 255));
        jbEquipamentos.setForeground(new java.awt.Color(204, 204, 204));
        jbEquipamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbEquipamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbEquipamentos.setBorderPainted(false);
        jbEquipamentos.setFocusCycleRoot(true);
        jbEquipamentos.setFocusable(false);
        jbEquipamentos.setOpaque(false);
        jbEquipamentos.setRequestFocusEnabled(false);
        jbEquipamentos.setRolloverEnabled(false);
        jbEquipamentos.setVerifyInputWhenFocusTarget(false);
        jbEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEquipamentosActionPerformed(evt);
            }
        });

        jbTecnicos.setBackground(new java.awt.Color(255, 255, 255));
        jbTecnicos.setForeground(new java.awt.Color(204, 204, 204));
        jbTecnicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbTecnicos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbTecnicos.setBorderPainted(false);
        jbTecnicos.setFocusCycleRoot(true);
        jbTecnicos.setFocusable(false);
        jbTecnicos.setOpaque(false);
        jbTecnicos.setRequestFocusEnabled(false);
        jbTecnicos.setRolloverEnabled(false);
        jbTecnicos.setVerifyInputWhenFocusTarget(false);

        jbChefias.setBackground(new java.awt.Color(255, 255, 255));
        jbChefias.setForeground(new java.awt.Color(204, 204, 204));
        jbChefias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbChefias.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbChefias.setBorderPainted(false);
        jbChefias.setFocusCycleRoot(true);
        jbChefias.setFocusable(false);
        jbChefias.setOpaque(false);
        jbChefias.setRequestFocusEnabled(false);
        jbChefias.setRolloverEnabled(false);
        jbChefias.setVerifyInputWhenFocusTarget(false);

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setForeground(new java.awt.Color(204, 204, 204));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/exit2.jpg"))); // NOI18N
        btSair.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btSair.setBorderPainted(false);
        btSair.setFocusCycleRoot(true);
        btSair.setFocusable(false);
        btSair.setOpaque(false);
        btSair.setRequestFocusEnabled(false);
        btSair.setRolloverEnabled(false);
        btSair.setVerifyInputWhenFocusTarget(false);
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/logoSuporteTI2.png"))); // NOI18N

        jbOrgaos.setBackground(new java.awt.Color(255, 255, 255));
        jbOrgaos.setForeground(new java.awt.Color(204, 204, 204));
        jbOrgaos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbOrgaos.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbOrgaos.setBorderPainted(false);
        jbOrgaos.setFocusCycleRoot(true);
        jbOrgaos.setFocusable(false);
        jbOrgaos.setOpaque(false);
        jbOrgaos.setRequestFocusEnabled(false);
        jbOrgaos.setRolloverEnabled(false);
        jbOrgaos.setVerifyInputWhenFocusTarget(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        jbRelatorio.setForeground(new java.awt.Color(204, 204, 204));
        jbRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-relatorio.png"))); // NOI18N
        jbRelatorio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbRelatorio.setBorderPainted(false);
        jbRelatorio.setFocusCycleRoot(true);
        jbRelatorio.setFocusable(false);
        jbRelatorio.setOpaque(false);
        jbRelatorio.setRequestFocusEnabled(false);
        jbRelatorio.setRolloverEnabled(false);
        jbRelatorio.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jbControle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbChefias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbOrgaos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbChefias, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEquipamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbControle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOrgaos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null,"Sistema Encerrado.\nVolte Sempre");
       dispose();
       System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void jbEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEquipamentosActionPerformed
        ViewStatus viewport= new ViewStatus();
        viewport.setSTATUS(true);
        this.status = viewport.getSTATUS();
        this.guiEquipamento = new GUIEquipamento(this.status);
        this.guiEquipamento.setVisible(true);
        viewport.verificaStatus();
    }//GEN-LAST:event_jbEquipamentosActionPerformed

    	
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            boolean status = false;
            public void run() {
                new GUIMenu(status).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbChefias;
    private javax.swing.JButton jbControle;
    private javax.swing.JButton jbEquipamentos;
    private javax.swing.JButton jbOrgaos;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JButton jbTecnicos;
    // End of variables declaration//GEN-END:variables
}
