/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.smagp.controle.estoque_ti.gui;

import java.net.URL;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author AllexOnRails
 */
public class GUIMenu extends javax.swing.JFrame {

    
    private JButton createImageButton(String texto, String uriAbsoluta) {
        URL uri = getClass().getResource(uriAbsoluta);
        JButton button = new JButton(texto, new ImageIcon(uri));
        button.setVerticalTextPosition(AbstractButton.BOTTOM);
        button.setHorizontalTextPosition(AbstractButton.CENTER);

        return button;
    }
    
    
    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        dispose();
        setUndecorated(true);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbControle1 = new javax.swing.JButton();
        jbControle2 = new javax.swing.JButton();
        jbControle3 = new javax.swing.JButton();
        jbControle4 = new javax.swing.JButton();
        jbControle5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbControle1.setBackground(new java.awt.Color(255, 255, 255));
        jbControle1.setForeground(new java.awt.Color(204, 204, 204));
        jbControle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbControle1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbControle1.setBorderPainted(false);
        jbControle1.setFocusCycleRoot(true);
        jbControle1.setFocusable(false);
        jbControle1.setOpaque(false);
        jbControle1.setRequestFocusEnabled(false);
        jbControle1.setRolloverEnabled(false);
        jbControle1.setVerifyInputWhenFocusTarget(false);
        jbControle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbControle1ActionPerformed(evt);
            }
        });

        jbControle2.setBackground(new java.awt.Color(255, 255, 255));
        jbControle2.setForeground(new java.awt.Color(204, 204, 204));
        jbControle2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbControle2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbControle2.setBorderPainted(false);
        jbControle2.setFocusCycleRoot(true);
        jbControle2.setFocusable(false);
        jbControle2.setOpaque(false);
        jbControle2.setRequestFocusEnabled(false);
        jbControle2.setRolloverEnabled(false);
        jbControle2.setVerifyInputWhenFocusTarget(false);
        jbControle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbControle2ActionPerformed(evt);
            }
        });

        jbControle3.setBackground(new java.awt.Color(255, 255, 255));
        jbControle3.setForeground(new java.awt.Color(204, 204, 204));
        jbControle3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbControle3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbControle3.setBorderPainted(false);
        jbControle3.setFocusCycleRoot(true);
        jbControle3.setFocusable(false);
        jbControle3.setOpaque(false);
        jbControle3.setRequestFocusEnabled(false);
        jbControle3.setRolloverEnabled(false);
        jbControle3.setVerifyInputWhenFocusTarget(false);
        jbControle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbControle3ActionPerformed(evt);
            }
        });

        jbControle4.setBackground(new java.awt.Color(255, 255, 255));
        jbControle4.setForeground(new java.awt.Color(204, 204, 204));
        jbControle4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbControle4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbControle4.setBorderPainted(false);
        jbControle4.setFocusCycleRoot(true);
        jbControle4.setFocusable(false);
        jbControle4.setOpaque(false);
        jbControle4.setRequestFocusEnabled(false);
        jbControle4.setRolloverEnabled(false);
        jbControle4.setVerifyInputWhenFocusTarget(false);
        jbControle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbControle4ActionPerformed(evt);
            }
        });

        jbControle5.setBackground(new java.awt.Color(255, 255, 255));
        jbControle5.setForeground(new java.awt.Color(204, 204, 204));
        jbControle5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/icone-plano.png"))); // NOI18N
        jbControle5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbControle5.setBorderPainted(false);
        jbControle5.setFocusCycleRoot(true);
        jbControle5.setFocusable(false);
        jbControle5.setOpaque(false);
        jbControle5.setRequestFocusEnabled(false);
        jbControle5.setRolloverEnabled(false);
        jbControle5.setVerifyInputWhenFocusTarget(false);
        jbControle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbControle5ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/smagp/controle/estoque_ti/resources/SuporteTI-2013.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jbControle1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbControle2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbControle3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbControle4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbControle5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbControle5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbControle4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbControle3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbControle2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbControle1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    	
    private void jbControle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbControle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbControle1ActionPerformed

    private void jbControle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbControle2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbControle2ActionPerformed

    private void jbControle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbControle3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbControle3ActionPerformed

    private void jbControle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbControle4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbControle4ActionPerformed

    private void jbControle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbControle5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbControle5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbControle1;
    private javax.swing.JButton jbControle2;
    private javax.swing.JButton jbControle3;
    private javax.swing.JButton jbControle4;
    private javax.swing.JButton jbControle5;
    // End of variables declaration//GEN-END:variables
}
